#! /bin/bash
srcdir=~/source/go/src/oops/common/pb
srcdir2=~/source/go/src/oops/pd
destdir=~/source/mass/trunk/data/NetMessage/protobuf_kange/

for v in `ls $destdir`; do
    if [ -f $srcdir/$v ] ; then
        cp $srcdir/$v $destdir/$v || true
    else
        cp $srcdir2/$v $destdir/$v || true
    fi
done
